# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ymanchon <ymanchon@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/13 16:21:19 by ymanchon          #+#    #+#              #
#    Updated: 2024/07/07 19:22:46 by ymanchon         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC =	cc

AR =  ar -rcs

SRCS = 	./binary_tree/btree_apply_infix.c \
		./binary_tree/btree_apply_prefix.c \
		./binary_tree/btree_apply_suffix.c \
		./binary_tree/btree_cmp.c \
		./binary_tree/btree_create_node.c \
		./binary_tree/btree_insert_data.c \
		./binary_tree/btree_search_item.c \
		./binary_tree/btree_size.c \
		./binary_tree/btree_strict_size.c \
		./gnl/get_next_line_utils_bonus.c \
		./gnl/get_next_line_bonus.c \
		./lst/ft_lstadd_back_bonus.c \
		./lst/ft_lstadd_front_bonus.c \
		./lst/ft_lstclear_bonus.c \
		./lst/ft_lstdelone_bonus.c \
		./lst/ft_lstiter_bonus.c \
		./lst/ft_lstlast_bonus.c \
		./lst/ft_lstmap_bonus.c \
		./lst/ft_lstnew_bonus.c \
		./lst/ft_lstsize_bonus.c \
		./mem/dfree.c \
		./mem/freemem.c \
		./mem/freemexit.c \
		./mem/ft_bzero.c \
		./mem/ft_calloc.c \
		./mem/ft_memchr.c \
		./mem/ft_memcmp.c \
		./mem/ft_memcpy.c \
		./mem/ft_memmove.c \
		./mem/ft_memset.c \
		./parsing/ft_isspace.c \
		./parsing/ft_rev_isspace.c \
		./parsing/ft_rev_isspaceptr.c \
		./parsing/owsequence.c \
		./str/ft_strtolower.c \
		./str/ft_strtoupper.c \
		./str/ft_split.c \
		./str/ft_strchr.c \
		./str/ft_strdup.c \
		./str/ft_strndup.c \
		./str/ft_striteri.c \
		./str/ft_strjoin.c \
		./str/ft_strsjoin.c \
		./str/ft_strlen.c \
		./str/ft_strmapi.c \
		./str/ft_strncmp.c \
		./str/ft_strcmp.c \
		./str/ft_strrchr.c \
		./str/ft_strtrim.c \
		./str/ft_strlcpy.c \
		./str/ft_strlcat.c \
		./str/ft_strnstr.c \
		./str/ft_substr.c \
		./str/strdelete.c \
		./str/strerase.c \
		./str/strinsert.c \
		./utils/ft_abs.c \
		./utils/ft_count_words.c \
		./utils/ft_intlen.c \
		./utils/ft_convert_base2.c \
		./utils/ft_convert_base.c \
		./zbasic/ft_atoi.c \
		./zbasic/ft_isalnum.c \
		./zbasic/ft_isalpha.c \
		./zbasic/ft_isascii.c \
		./zbasic/ft_isdigit.c \
		./zbasic/ft_isprint.c \
		./zbasic/ft_itoa.c \
		./zbasic/ft_tolower.c \
		./zbasic/ft_toupper.c \
		./zbasic/ft_putchar_fd.c \
		./zbasic/ft_putendl_fd.c \
		./zbasic/ft_putnbr_fd.c \
		./zbasic/ft_putstr_fd.c \

OBJS_DIR =	objs

OBJS =			$(SRCS:%.c=$(OBJS_DIR)/%.o)

INCLUDES = -I .

CFLAGS =	-Wall -Wextra -Werror -fPIE

PRINTF_P = ./ft_printf

all: $(NAME)

$(NAME): $(OBJS)
	make -C $(PRINTF_P) re
	$(AR) -o $@ $(PRINTF_P)/objs/*/*.o
	$(AR) -o $@ $(OBJS)

$(OBJS_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@

clean:
	rm $(OBJS_DIR) -rf

fclean: clean
	rm $(NAME) -f

re: fclean all

.PHONY: all clean fclean re